version: '3'
services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: teste_php
    volumes:
      - ./app:/var/www/html
    ports:
      - 8081:80


  nginx:
    image: bitnami/nginx:1.23.1-debian-11-r19
    container_name: nginx-app
    volumes:
      - ./home/nicolas/Documentos/Teste/app:/var/www/html  # Paradinha do caminho absoluto 
      - ./nginx/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/nginx.conf:ro
    ports:
    - 8080:80
