name: Deploy AWS EC2 com SSM

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Capturando código atualizado
        uses: actions/checkout@v3

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_INSTANCE_REGION }}
          aws-access-key-id: ${{ secrets.AWS_EC2_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_EC2_ACCESS_KEY }}
          instance-ids: ${{ secrets.AWS_INSTANCE_ID }}
          working-directory: /home/ec2-user/Treinamento
          command: echo "testando" >> teste.txt


      - name: Capturando o retorno
        run: echo "O ID do comando é ${{ steps.ssm.outputs.command-id }}"